{% set name = "sqlalchemy2-stubs" %}
{% set version = "0.0.2a37" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy2-stubs-{{ version }}.tar.gz
  sha256: 619bd131f8ad7eeb88af8dfabb0e6ba07593db91868cdc49674d2cd4ca61e986

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - typing_extensions >=3.7.4

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.sqlalchemy.org
  dev_url: https://github.com/sqlalchemy/sqlalchemy2-stubs
  summary: Typing Stubs for SQLAlchemy 1.4
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
